version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t bioinfo-web web/
      - docker tag bioinfo-web:latest 646607356140.dkr.ecr.ap-southeast-1.amazonaws.com/bioinfo-web:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 646607356140.dkr.ecr.ap-southeast-1.amazonaws.com/bioinfo-web:latest
      - printf '[{"name":"nginx","imageUri":"%s"}]' 646607356140.dkr.ecr.ap-southeast-1.amazonaws.com/bioinfo-web:latest > imagedefinitions.json  
artifacts:
        files: imagedefinitions.json
